/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSearchRouteImport } from './routes/$locale/search'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as LocaleGuidesIndexRouteImport } from './routes/$locale/guides/index'
import { Route as LocaleDevIndexRouteImport } from './routes/$locale/dev/index'
import { Route as LocaleAdvancedIndexRouteImport } from './routes/$locale/advanced/index'
import { Route as LocaleDevApiRouteImport } from './routes/$locale/dev/api'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGuidesIndexRoute = LocaleGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDevIndexRoute = LocaleDevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAdvancedIndexRoute = LocaleAdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDevApiRoute = LocaleDevApiRouteImport.update({
  id: '/dev/api',
  path: '/dev/api',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dev/api': typeof LocaleDevApiRoute
  '/$locale/advanced/': typeof LocaleAdvancedIndexRoute
  '/$locale/dev/': typeof LocaleDevIndexRoute
  '/$locale/guides/': typeof LocaleGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/dev/api': typeof LocaleDevApiRoute
  '/$locale/advanced': typeof LocaleAdvancedIndexRoute
  '/$locale/dev': typeof LocaleDevIndexRoute
  '/$locale/guides': typeof LocaleGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dev/api': typeof LocaleDevApiRoute
  '/$locale/advanced/': typeof LocaleAdvancedIndexRoute
  '/$locale/dev/': typeof LocaleDevIndexRoute
  '/$locale/guides/': typeof LocaleGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/$'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/dev/api'
    | '/$locale/advanced/'
    | '/$locale/dev/'
    | '/$locale/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/$'
    | '/$locale/search'
    | '/$locale'
    | '/$locale/dev/api'
    | '/$locale/advanced'
    | '/$locale/dev'
    | '/$locale/guides'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/$'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/dev/api'
    | '/$locale/advanced/'
    | '/$locale/dev/'
    | '/$locale/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/': {
      id: '/$locale/guides/'
      path: '/guides'
      fullPath: '/$locale/guides/'
      preLoaderRoute: typeof LocaleGuidesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dev/': {
      id: '/$locale/dev/'
      path: '/dev'
      fullPath: '/$locale/dev/'
      preLoaderRoute: typeof LocaleDevIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/advanced/': {
      id: '/$locale/advanced/'
      path: '/advanced'
      fullPath: '/$locale/advanced/'
      preLoaderRoute: typeof LocaleAdvancedIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dev/api': {
      id: '/$locale/dev/api'
      path: '/dev/api'
      fullPath: '/$locale/dev/api'
      preLoaderRoute: typeof LocaleDevApiRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleDevApiRoute: typeof LocaleDevApiRoute
  LocaleAdvancedIndexRoute: typeof LocaleAdvancedIndexRoute
  LocaleDevIndexRoute: typeof LocaleDevIndexRoute
  LocaleGuidesIndexRoute: typeof LocaleGuidesIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleDevApiRoute: LocaleDevApiRoute,
  LocaleAdvancedIndexRoute: LocaleAdvancedIndexRoute,
  LocaleDevIndexRoute: LocaleDevIndexRoute,
  LocaleGuidesIndexRoute: LocaleGuidesIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
